version: '3.9'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  metabase:
    image: metabase/metabase
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    volumes:
      - metabase-data:/metabase-data
    
volumes:
  mongo-data:
    driver: local
  metabase-data:
    driver: local