version: '3.9'

services:

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  metabase:
    image: metabase/metabase
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    volumes:
      - metabase-data:/metabase-data

#-----------------------------ime baze-----------------------------------------------------------------------
# mongodb://mongodb:27017/tennis-optimized - korsititi ovaj connection string prilikom povezivanja na mongoDB
    
volumes:
  mongo-data:
    driver: local
  metabase-data:
    driver: local